package me.devnatan.katan.common

object EnvKeys {

    const val ENVIRONMENT = "KATAN_ENV"
    const val LOCALE = "KATAN_LOCALE"
    const val ROOT_DIR = "KATAN_ROOT"
    const val DOCKER_URI = "KATAN_DOCKER_URI"
    const val DOCKER_TLS_VERIFY = "KATAN_DOCKER_TLS_VERIFY"
    const val DOCKER_TLS_CERTPATH = "KATAN_DOCKER_TLS_CERTPATH"
    const val WS_ENABLED = "KATAN_WS_ENABLED"
    const val WS_DEPLOY_USE_SSL = "KATAN_WS_SSL_ENABLED"
    const val WS_DEPLOY_SSL_KEYALIAS = "KATAN_WS_SSL_KEY_ALIAS"
    const val WS_DEPLOY_SSL_KEYSTORE_PASSWORD = "KATAN_WS_SSL_KEYSTORE_PASSWORD"
    const val WS_DEPLOY_SSL_PRIVATEKEY_PASSWORD = "KATAN_WS_SSL_PRIVATEKEY_PASSWORD"
    const val WS_DEPLOY_HOST = "KATAN_WS_HOST"
    const val WS_DEPLOY_PORT = "KATAN_WS_PORT"
    const val WS_DEPLOY_SSL_PORT = "KATAN_WS_SSL_PORT"
    const val WS_REVERSE_PROXIED = "KATAN_WS_REVERSE_PROXIED"
    const val WS_CORS_DISABLED = "KATAN_WS_CORS_DISABLED"

}