dependencies {
    implementation(projects.configuration)
    implementation(projects.eventsDispatcher)
    implementation(projects.configuration)
    implementation(projects.http.httpShared)
    implementation(projects.services.idService)
    implementation(projects.services.networkService)
    implementation(projects.services.fsService)
    implementation(projects.services.blueprintService)
    implementation(libs.hibernateValidator)
    implementation(libs.exposed.dao)
    implementation(libs.koin.ktor)
    implementation(libs.ktor.server.auth)
    implementation(libs.ktor.server.feature.resources)
    implementation(libs.ktor.serialization.kotlinx.json)
    testImplementation(projects.http.httpTest)
}