package me.devnatan.katan.webserver

const val INVALID_ACCESS_TOKEN_ERROR = 1000
const val ACCOUNT_MISSING_CREDENTIALS_ERROR = 2001
const val ACCOUNT_INVALID_CREDENTIALS_ERROR = 2002
const val ACCOUNT_ALREADY_EXISTS_ERROR = 2003
const val ACCOUNT_NOT_FOUND_ERROR = 2004
const val SERVER_FS_DISK_NOT_FOUND = 3001